title: "Jin H Kim"
description: "Associate Professor · AI Safety & CPS · Gyeongsang National University"

# GitHub Pages용 리포지토리 정보 (github-metadata용)
repository: "jhkim07/jhkim07.github.io"

# 사이트 기본 설정
baseurl: ""      # GitHub Pages user site라서 빈 문자열
url: "https://jin-kim.net"

markdown: kramdown
permalink: pretty

# 빌드시 제외할 것들
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - _site

# 필요하면 향후 plugins 추가 가능
# plugins:
#   - jekyll-seo-tag

plugins:
  - jekyll-sitemap